### ISSUE TITLE
Too big errors for the sample club

### ISSUE THREAD

**Issue by crusader2000** [ujwal-narayan/Clubs-Website#5]
![Screenshot from 2019-12-19 17-49-16](https://user-images.githubusercontent.com/43775333/71173276-44007a00-2288-11ea-8822-2a2f05226ccb.png)

**Comment by ujwal-narayan** [comment]
Are you sure you're using the right version?

**Comment by 20161302animesh** [comment]
Hi Ujwal!

Getting similar errors here as well.
![Screenshot from 2019-12-30 17-57-17](https://user-images.githubusercontent.com/15274434/71582005-1f30c000-2b2e-11ea-81c1-0995b872c9ec.png)

**Comment by crusader2000** [comment]
@ujwal-narayan  yes

**Comment by ujwal-narayan** [comment]
It's most likely an issue with your installation of the theme. This should fix it. 
Do this in the root dir of your project.
```
git clone https://github.com/themefisher/kross-hugo.git themes/kross-hugo-portfolio-template/   
```
If it does not, feel free to open the issue
