### ISSUE TITLE
Background colour not loading

### ISSUE THREAD

**Issue by bishboi** [ujwal-narayan/Clubs-Website#7]
There is a problem loading the background colour 

![Screenshot from 2020-01-07 16-36-20](https://user-images.githubusercontent.com/44214840/71891169-06e32580-316c-11ea-85cc-91383fcf4cd6.png)
![Screenshot from 2020-01-07 16-36-24](https://user-images.githubusercontent.com/44214840/71891172-09de1600-316c-11ea-8c96-d2d19f4679d2.png)

**Comment by ujwal-narayan** [comment]
Could you give the complete list of commands run so that I can replicate this issue

**Comment by bishboi** [comment]
i just used ```hugo server``` 
the background wasn't loading initially as well 
( before i changed anything).
the theme on the other hand is working fine as I have shown in the other screenshot

**Comment by crusader2000** [comment]
![Screenshot from 2020-05-19 16-30-30](https://user-images.githubusercontent.com/43775333/82318262-2d07b480-99ed-11ea-9a8f-fefa8ed2ef92.png)

Add the highlighted line in config.toml

**Comment by Dineshg49** [comment]
I made the following change still the colour is not updated
![Screenshot from 2020-05-22 17-28-10](https://user-images.githubusercontent.com/54172397/82665685-f1b9ef80-9c51-11ea-9861-1568e092be74.png)
![Screenshot from 2020-05-22 17-29-01](https://user-images.githubusercontent.com/54172397/82665690-f67ea380-9c51-11ea-9d94-6b9b56756997.png)

**Comment by crusader2000** [comment]
Add this line too in layouts/partials/head.html

![Screenshot from 2020-05-23 11-38-13](https://user-images.githubusercontent.com/43775333/82723010-19a86200-9ce9-11ea-9e1c-0dcd8e50240c.png)
